#:schema https://raw.githubusercontent.com/YunoHost/apps/main/schemas/manifest.v2.schema.json

packaging_format = 2

id = "stalwart"
name = "Stalwart"
description.en = " All-in-one Mail & Collaboration server. Secure, scalable and fluent in every protocol (IMAP, JMAP, SMTP, CalDAV, CardDAV, WebDAV). "

version = "0.16.1~ynh1"

maintainers = ["Thovi98"]

[upstream]
license = "AGPL-3.0"
website = "https://stalw.art/"
admindoc = "https://stalw.art/docs/category/getting-started"
code = "https://github.com/stalwartlabs/stalwart"

cpe = "cpe:2.3:a:stalw:stalwart"
fund = "https://opencollective.com/stalwart"

[integration]
yunohost = ">= 12.1.39"
helpers_version = "2.1"
architectures = ["amd64", "arm64"]
multi_instance = true

ldap = true
sso = true

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.admin]
    # this is a generic question - ask strings are automatically handled by YunoHost's core
    type = "user"

    [install.password]
    # this is a generic question - ask strings are automatically handled by YunoHost's core
    # Note that user-provided passwords questions are not automatically saved as setting
    help.en = "Use the help field to add an information for the admin about this question."
    help.fr = "Utilisez le champ aide pour ajouter une information à l'intention de l'administrateur à propos de cette question."
    type = "password"

[resources]
    [resources.sources]

    [resources.sources.main]
    amd64.url = "https://github.com/stalwartlabs/stalwart/releases/download/v0.16.2/stalwart-x86_64-unknown-linux-gnu.tar.gz"
    amd64.sha256 = "cc43c1cb149fb3d2d02cd996027269223086915834ad7c5abdee4570ba48ade1"
    arm64.url = "https://github.com/stalwartlabs/stalwart/releases/download/v0.16.0/stalwart-aarch64-unknown-linux-gnu.tar.gz"
    arm64.sha256 = "15e946a17688e125e164cf0bd13d85a0fcf540c64142f8ab8226f034b98c5689"

    in_subdir = false

    autoupdate.strategy = "latest_github_release"
    autoupdate.asset.amd64 = ".*x86_64-*\\.tar.gz$"
    autoupdate.asset.arm64 = ".*aarch64-*\\.tar.gz$"

    [resources.sources.cli]
    amd64.url = "https://github.com/stalwartlabs/cli/releases/download/v1.0.3/stalwart-cli-x86_64-unknown-linux-gnu.tar.xz"
    amd64.sha256 = "0fc0b14a9c5e3de47c8ff4d0d9816e4d5b3407184af39ab682d356c077310a7e"
    arm64.url = "https://github.com/stalwartlabs/cli/releases/download/v1.0.0/stalwart-cli-aarch64-unknown-linux-gnu.tar.xz"
    arm64.sha256 = "de8bbd84bf73e7fa17bd2a242d22c359efc74def98f44632df2a5b197357c27c"

    autoupdate.strategy = "latest_github_release"
    autoupdate.asset.amd64 = ".*x86_64-*\\.tar.gz$"
    autoupdate.asset.arm64 = ".*aarch64-*\\.tar.gz$"

    [resources.system_user]
    allow_email = true

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"
    main.auth_header = false

    #admin.url = "/admin"
    #admin.auth_header = false
    #admin.show_tile = false
    #admin.protected = true

    [resources.ports]
    main.default = 8080

    [resources.apt]
    packages = "redis-server"

    [resources.database]
    type = "postgresql"
