#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source /usr/share/yunohost/helpers

#=================================================
# INITIALIZE AND STORE SETTINGS
#=================================================

token=$(ynh_string_random --length=45 | base64)
ynh_app_setting_set --key=token --value=$token

ynh_app_setting_set --key=password --value=$password


#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

ynh_setup_source --dest_dir="$install_dir"
ynh_setup_source --dest_dir="$install_dir" --source_id="cli"

chmod 750 "$install_dir"/stalwart
chmod 750 "$install_dir"/stalwart-cli

#=================================================
# APP INITIAL CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration files..."

ynh_config_add --template="config.json" --destination="$install_dir/config.json"
ynh_config_add --template=".env" --destination="$install_dir/.env"

ynh_config_add_systemd
yunohost service add "$app" --description="Stalwart" --log="/var/log/$app/$app.log"

ynh_systemctl --service="$app" --action="start"

sleep 15

# This has to be done once the service is started as it looks for the used url
ynh_script_progression "Creating admin user..."
pushd $install_dir
    export STALWART_URL=http://localhost:"$port"
    export STALWART_RECOVERY_MODE=1
    export STALWART_RECOVERY_ADMIN="$admin":"$password"

    ./stalwart-cli --insecure --user $admin --password $password create domain --field name=$domain
    ./stalwart-cli --insecure --user $admin --password $password create account/user --field name=$admin --field domainid=b
    ./stalwart-cli --insecure --user $admin --password $password update Account c --field 'credentials={"0":{"@type":"Password","secret":"$password"}}'
    ./stalwart-cli --insecure --user $admin --password $password update Account c --field '"roles"={"@type": "Admin"}'
popd


#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

ynh_config_add_nginx

ynh_config_add_logrotate

# Create a dedicated Fail2Ban config
# ynh_config_add_fail2ban --logpath="/var/log/nginx/${domain}-error.log" --failregex="Regex to match into the log for a failed login"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

#ynh_systemctl --service="$app" --action="restart"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
